---

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

stages:
  - 🚚 publish

variables:
  APP_NAME: magic-helpdesk

  # Secrets (set in GitLab CI/CD settings)
  # - AWS IAM id/secret key for 'bas-gitlab-ci-magic-helpdesk' user
  #   - AWS_ACCESS_KEY_ID: "[Sensitive]"
  #   - AWS_SECRET_ACCESS_KEY: "[Sensitive]"
  # == Notes ==

image:
  name: governmentpaas/awscli:latest
  entrypoint: [""]

publish:
  stage: 🚚 publish
  script:
    - aws s3 sync --delete public/ s3://magic-helpdesk.web.bas.ac.uk/
  environment:
    name: production
    url: https://magic-helpdesk.web.bas.ac.uk
  rules:
    -
      changes:
        - public/**.*
