---
  version: "2"

  services:
    web:
      image: nginx:alpine
      volumes:
        - ./support/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./public:/usr/share/nginx/html/public
      ports:
        - "9000:9000"
